name: CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-musl
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    
    - name: Check code formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
       
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
        
    - name: Install musl-tools
      run: sudo apt-get install -y musl-tools
    
    - name: Test Lambda build
      run: |
        chmod +x ./scripts/build-lambda.sh
        ./scripts/build-lambda.sh
        
    - name: Verify bootstrap.zip exists
      run: |
        if [ ! -f target/lambda/bootstrap.zip ]; then
          echo "bootstrap.zip was not created properly"
          exit 1
        fi
