name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build Lambda Package
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/lockbox-box-service bootstrap
          zip function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
          
      - name: Deploy with SAM
        run: |
          # Set AWS region from secrets or default to us-east-1
          AWS_REGION="${{ secrets.AWS_REGION }}"
          AWS_REGION="${AWS_REGION:-us-east-1}"
          echo "Using AWS region: $AWS_REGION"
          
          # Create S3 bucket for deployment if it doesn't exist
          BUCKET_NAME="lockbox-deployment-bucket-$AWS_REGION"
          aws s3 mb "s3://$BUCKET_NAME" --region "$AWS_REGION" || true
          
          # Deploy using SAM with increased timeout for Cognito resources
          sam deploy --template-file template.yaml \
            --stack-name lockbox-box-service \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --no-confirm-changeset \
            --s3-bucket "$BUCKET_NAME" \
            --region "$AWS_REGION" \
            --no-fail-on-empty-changeset \
            --parameter-overrides "Stage=prod"
            
      - name: Display Cognito Outputs
        run: |
          # Get and display the Cognito User Pool ID and Client ID
          AWS_REGION="${{ secrets.AWS_REGION }}"
          AWS_REGION="${AWS_REGION:-us-east-1}"
          
          echo "Getting stack outputs..."
          aws cloudformation describe-stacks --stack-name lockbox-box-service --region "$AWS_REGION" --query "Stacks[0].Outputs" --output table
